name: "USE (Unnamed Sonic Engine) Build"

on: 
  workflow_dispatch:
    inputs:
      # Most of these parameters are available on the Setup Script
      # You can only change them if:
      # - You called the script on terminal and not double-clicked it
      # - You change the behavior of the script (lol)

      platform:
        description: "Select the platform to set up the environment for."
        type: choice
        required: true
        default: "cpp"
        options:
          - cpp # Windows / Linux / MachintoshOS
          - hl # HashLink
          - neko # NekoVM
          # Android is not available until the game is playable on Mobile and its build works (stupid Lime 8.2 ...)
          ## CURRENT PROBLEM: Lime inserts an "if" on AndroidManifest causing it to abort the build if not removed manually.
      build-type:
        description: "Select the build type of the game."
        type: choice
        required: true
        default: "release"
        options:
          - debug
          - release
          - final

      # NOTE: I didn't test it, tell me if it works!
      arch-32:
        description: "Should your build be for 32bits?"
        type: boolean
        default: false

      runner-os:
        description: "Select which OS runner to use for the build."
        type: choice
        required: true
        default: "ubuntu-latest"
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  setup:
    name: "Setup the build environment"
    permissions: write-all
    runs-on: ${{ github.event.inputs.runner-os }}
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Haxe 4.3.7"
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: "4.3.7"

      - name: "Run Setup Script - Install Dependencies"
        run: pwsh -File "./_project/build/setup.ps1" -MenuOption 0

      - name: "Cache Haxe & Libraries"
        uses: actions/cache@v3
        with:
          path: ${{ runner.os == 'Windows' && '%USERPROFILE%\\.haxelib' || '~/.haxelib' }}
          key: ${{ runner.os }}-haxelib-${{ hashFiles('*.hxml', 'hmm.json', 'Project.hxp') }}
          restore-keys: ${{ runner.os }}-haxelib-


  build:
    needs: setup
    runs-on: ${{ github.event.inputs.runner-os }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Restore Haxe Cache"
        uses: actions/cache@v3
        with:
          path: ${{ runner.os == 'Windows' && '%USERPROFILE%\\.haxelib' || '~/.haxelib' }}
          key: ${{ runner.os }}-haxelib-${{ hashFiles('*.hxml', 'hmm.json', 'Project.hxp') }}

      - name: "Build the Game"
        run: pwsh -File "./_project/build/build.ps1" -Platform ${{ github.event.inputs.platform }} -BuildType ${{ github.event.inputs.build-type }} -Action build -Is32Bits ${{ github.event.inputs.arch-32 }}
        # We can't use: run, -watch, test; because it's a online VM, not a local one

      - run: echo "Uploading files..."

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.event.inputs.platform }}-${{ github.event.inputs.build-type }}
          path: export/${{ github.event.inputs.build-type }}/${{ github.event.inputs.platform }}/bin
